#!/bin/bash

# simple script to activate tor-proxy

#todo: check if interface is free for tor, else error or autochoose free

#path=/lib/systemd/system

if [[ $1 == "-disable" ]]; then
        echo "Disabling tor-proxy..."
        systemctl disable tor

elif [[ $1 == "-enable" ]]; then
    if [[ ! $(systemctl status tor | grep 'Active: active (running') ]]; then
	    echo "Enabling tor-proxy..."
        systemctl enable --now tor
    else
        echo "Unknown error with service, check manually."
    fi

elif [[ $1 == "-h" ]]; then
	echo ''
	echo 'Miniscript for control of tor-proxy.'
    echo ''
    echo 'tormod [opt1] [opt2]'
	echo ''
    echo '[opt1]:'
	echo '-disable      disable tor-proxy'
	echo ''
	echo '-enable       enable tor-proxy'
	echo '              [opt2] interface for tor-entry, e.g. wlan0'
    echo ''
	echo ''
	echo ''
else
	echo ''
	echo 'Use -h for help-'
	echo ''
fi

